version: '3'

services:

  webapp:
    build:
      context: backend
      dockerfile: Dockerfile-dev
    networks:
      - link-now-network
    depends_on:
      - redis
      - mongo
      - aiohttp-mongdb-unit
      - aiohttp-redis-unit
    volumes:
      - ./backend/:/backend
      - ./common_file/:/common_file
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    command:
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /common_file/wait-for-it.py mongo:27017 redis:6379 aiohttp-redis-unit:8081 aiohttp-mongdb-unit:9988 python3 server.py
    ports:
      - "9040:9040"

  aiohttp-mongdb-unit:
    build:
      context: aiohttp_mongdb_unit
      dockerfile: Dockerfile-dev
    networks:
      - link-now-network
    depends_on:
      - redis
      - mongo
    volumes:
      - ./aiohttp_mongdb_unit/:/backend
      - ./common_file/:/common_file
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    command:
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /common_file/wait-for-it.py mongo:27017 redis:6379 python3 main.py

  aiohttp-redis-unit:
    build:
      context: aiohttp_redis_unit
      dockerfile: Dockerfile-dev
    networks:
      - link-now-network
    depends_on:
      - redis
      - mongo
    volumes:
      - ./aiohttp_redis_unit/:/backend
      - ./common_file/:/common_file
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    command:
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /common_file/wait-for-it.py mongo:27017 redis:6379 python3 main.py

  redis:
    image: "redis:5.0-alpine"
    networks:
      - link-now-network
    ports:
      - "36379:6379"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'

  mongo:
    image: mongo:3.6
    networks:
      - link-now-network
    command:
      - --dbpath=/data/db
    volumes:
      - ./volume/mongo:/data/db
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'

  nginx:
    image: nginx:1.17
    networks:
      - link-now-network
    depends_on:
      - redis
      - mongo
      - aiohttp-mongdb-unit
      - aiohttp-redis-unit
      - webapp
    volumes:
      - ./volume/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8899:80"

networks:
   link-now-network:
     driver: bridge
