version: '3'

services:

  mongo:
    command:
      - /bin/sh
      - -c
      - |
        echo "启动mongo"
        mongod --dbpath=/data/db --bind_ip_all --port 27017 &

        sleep 30

        echo "创建用户"
        mongo --port 27017 --eval 'db.createUser({
        user:"root",
        pwd:"123456",
        roles:[{
        role:"readWrite",
        db:"user"
        }]
        });
        db.auth("root", "123456");'
        echo "执行成功"

